services:
  n8n:
    image: n8nio/n8n:latest
    container_name: docker-n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
    volumes:
      # persistent data for workflows & credentials
      - ./data:/home/node/.n8n
    restart: unless-stopped
